#!/usr/bin/env bash

: "${PHP_PACKAGE:=php73}"

echo "Bootstrap ${PHP_PACKAGE}"

echo "Environment:"
env | sort

ls -la /opt
ls -la /opt/${PHP_PACKAGE};

/opt/${PHP_PACKAGE}/bin/php -c /opt/${PHP_PACKAGE}/php.ini /opt/${PHP_PACKAGE}/bootstrap.php;
